In [2]:
# import libraries

import pandas as pd
import numpy as np
from pathlib import Path

In [5]:
# defining input and output (= path with the file we want to create as the goal of this notebook)

INPUT_FILE = Path("data/social/raw/social_panel_clean.csv")

In [6]:
# let's read our previously created csv file with the aggregated social dimension data

df = pd.read_csv(
    INPUT_FILE,
    dtype={"plr_key": "string"}     # we have to read this as string, so the "0" at the beginning doesn't get lost
)

df["date"] = pd.to_datetime(df["date"])
df["year"] = df["date"].dt.year

df = df.sort_values(["plr_key", "year"]).reset_index(drop=True)

C:\Users\valer\AppData\Local\Temp\ipykernel_15168\2602385660.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["year"] = df["date"].dt.year

In [7]:
df = df.copy()

In [8]:
df.head()

,plr_key,plr_name,res_count,age_1,age_2,age_3,age_4,age_5,age_6,age_7,...,k16_foreign_res_share_pct,k6_foreign_res_share_change_2yr_pp,k17_non_eu_foreign_res_share_pct,k7_foreign_sgb2_transfer_recipients_share_pct,k9_res_simple_resid_loc_share_pct,k10_res_same_addr_5plus_years_share_pct,k11_migr_vol_2yr_avg_annual_pct,k12_net_migr_total_2yr_avg_annual_pct,k13_net_migr_under_6_2yr_avg_annual_pct,year
0,01100101,Stülerstraße,3419.0,156.0,143.0,28.0,442.0,1162.0,360.0,377.0,...,40.567,-1.306,70.440,8.554,0.0,55.917,38.361,0.507,-4.830,2020
1,01100101,Stülerstraße,3406.0,161.0,176.0,28.0,422.0,1144.0,356.0,404.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
2,01100101,Stülerstraße,3561.0,165.0,209.0,25.0,395.0,1271.0,375.0,403.0,...,43.302,2.735,70.752,9.447,0.0,52.642,37.777,2.144,4.939,2022
3,01100101,Stülerstraße,3680.0,140.0,225.0,31.0,476.0,1316.0,396.0,399.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
4,01100101,Stülerstraße,3580.0,165.0,203.0,49.0,466.0,1219.0,385.0,376.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024

In [31]:
less_than_1001 = df.query("res_count < 1001 or res_count.isna()")[['plr_key', 'plr_name']].drop_duplicates()

less_than_1001

       plr_key                plr_name
594   03300515     Blankenburger Süden
599   03300515    Blankenburger Süden
690   03400831            Pankower Tor
695   03400831           Pankower Tor
1014  04400725  Güterbahnhof Grunewald
1410  05300838              Gartenfeld
1422  05300840         Nonnendammallee
1560  06200418                 Landweg
3096  12200411     Schumacher-Quartier

In [19]:
df.loc[df['plr_name'] == 'Marzahner Chaussee', ['year', 'res_count']]

      year  res_count
2604  2020     2228.0
2605  2021     2221.0
2606  2022     2234.0
2607  2023     2253.0
2608  2024     2670.0

In [20]:
df.loc[
    df['plr_name'].str.contains('Marzahner Chaussee', na=False, case=False),
    ['plr_name', 'year', 'res_count']
]

                 plr_name  year  res_count
2604   Marzahner Chaussee  2020     2228.0
2605   Marzahner Chaussee  2021     2221.0
2606   Marzahner Chaussee  2022     2234.0
2607   Marzahner Chaussee  2023     2253.0
2608   Marzahner Chaussee  2024     2670.0
2609  Marzahner Chaussee   2025     2970.0