# Exploring Clusters

This notebook explores the clusters that were formed by the K-Means Clustering in the notebook `module_1_clustering.ipynb`. Specifically, the goal is to determine the structure of the clusters across the real-estate, social and commercial dimension.

##

In [23]:
#load packages
import pandas as pd 
import numpy as np
from sklearn.impute import KNNImputer

In [24]:
#load dataframes 
clusters = pd.read_csv("../../data/Module_1/cluster_assignments.csv", dtype={"plr_id": str})
features = pd.read_csv("../../data/final_datasets/dataset_0.csv", dtype={"plr_id": str})
ms = pd.read_csv("../../data/Module 2/target_milieuschutz.csv", dtype={"plr_id": str})

#define id columns and feature columns
id_cols = ["plr_id", "plr_name", "bez"]
feat_cols = [c for c in df.columns if c not in id_cols]

#impute missing values: 
X = features[feat_cols].copy()

# impute feature columns
X_imp = pd.DataFrame(
    KNNImputer(n_neighbors=3).fit_transform(X),
    columns=feat_cols, index=features.index,
)

#concat dataframe
df_imp = pd.concat([features[id_cols], X_imp], axis=1)

print(df_imp.shape, "| remaining NaN in feature columns:",
      int(df_imp[feat_cols].isna().sum().sum()))
df_imp.head(3)

(527, 45) | remaining NaN in feature columns: 0

,plr_id,plr_name,bez,re_miete_niveau,re_miete_trend,re_leerstandsquote,re_brw_niveau,re_brw_trend,re_dichte_all,soc_young_to_middle_adult_share_2025,...,com_share_min_30y_slope,com_share_min_40y_slope,com_share_solo_slope,com_share_10plus_slope,com_gastro_share_slope,com_entry_rate_slope,com_exit_rate_slope,com_n_gastro,re_altbau_share,re_neubau_share
0,01100101,Stülerstraße,01 - Mitte,22.7,2.142,3.050847,3890.584913,-0.326098,10.653753,0.460,...,0.001367,-0.000276,0.024083,0.002754,0.003153,-0.002800,0.001395,13.000000,0.118160,0.102663
1,01100102,Großer Tiergarten,01 - Mitte,20.3,1.059,4.557180,3440.019389,-0.426678,24.075666,0.479,...,0.003015,0.001063,0.028592,0.002506,0.004856,-0.000930,-0.000664,129.333333,0.228719,0.297506
2,01100103,Lützowstraße,01 - Mitte,23.0,1.356,1.863997,3541.826020,-0.440097,16.223680,0.455,...,0.001498,0.001101,0.032530,-0.001222,0.000177,-0.001019,0.000103,43.833333,0.323783,0.130135

In [25]:
#merge clusters 
df_merge1 = df_imp.merge(clusters, on="plr_id", how="left")
#check 
print(df_merge1.shape)

(527, 47)

In [27]:
#merge milieuschutz areas 
df = df_merge1.merge(ms, on = ['plr_id', 'plr_name', 'bez'], how = "left")
print(df.shape)
df.head(2)

(527, 49)

,plr_id,plr_name,bez,re_miete_niveau,re_miete_trend,re_leerstandsquote,re_brw_niveau,re_brw_trend,re_dichte_all,soc_young_to_middle_adult_share_2025,...,com_gastro_share_slope,com_entry_rate_slope,com_exit_rate_slope,com_n_gastro,re_altbau_share,re_neubau_share,cluster_3k,cluster_4k,milieu_anteil,milieu_majoritaet
0,01100101,Stülerstraße,01 - Mitte,22.7,2.142,3.050847,3890.584913,-0.326098,10.653753,0.460,...,0.003153,-0.00280,0.001395,13.000000,0.118160,0.102663,2,1,0.0,0
1,01100102,Großer Tiergarten,01 - Mitte,20.3,1.059,4.557180,3440.019389,-0.426678,24.075666,0.479,...,0.004856,-0.00093,-0.000664,129.333333,0.228719,0.297506,2,1,0.0,0

In [ ]:
#rename columns from german > english (ms = milieuschutz: protected area under § 172 BGB)
df.rename(columns={"milieu_anteil": "ms_portion", "milieu_majoritaet": "ms_binary"}, inplace = True)
df.head(2)

,plr_id,plr_name,bez,re_miete_niveau,re_miete_trend,re_leerstandsquote,re_brw_niveau,re_brw_trend,re_dichte_all,soc_young_to_middle_adult_share_2025,...,com_gastro_share_slope,com_entry_rate_slope,com_exit_rate_slope,com_n_gastro,re_altbau_share,re_neubau_share,cluster_3k,cluster_4k,ms_portion,ms_binary
0,01100101,Stülerstraße,01 - Mitte,22.7,2.142,3.050847,3890.584913,-0.326098,10.653753,0.460,...,0.003153,-0.00280,0.001395,13.000000,0.118160,0.102663,2,1,0.0,0
1,01100102,Großer Tiergarten,01 - Mitte,20.3,1.059,4.557180,3440.019389,-0.426678,24.075666,0.479,...,0.004856,-0.00093,-0.000664,129.333333,0.228719,0.297506,2,1,0.0,0